"""empty message

Revision ID: 7551f993abee
Revises: 
Create Date: 2021-01-10 01:13:20.110618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7551f993abee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('kakao_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('usertype', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('answer',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('kakao_id', sa.String(length=10), nullable=False),
    sa.Column('checkdate', sa.Date(), nullable=True),
    sa.Column('checktime', sa.DateTime(), nullable=True),
    sa.Column('checkstatus', sa.String(length=10), nullable=False),
    sa.Column('workplace', sa.String(length=10), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('unusual', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kakao_id'], ['user.kakao_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('user')
    # ### end Alembic commands ###
