"""empty message

Revision ID: 8e0cb190bf2d
Revises: 
Create Date: 2021-01-20 22:04:40.115519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0cb190bf2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('firstSend', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('secondSend', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('thirdSend', sa.Boolean(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('kakao_id', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('usertype', sa.String(length=10), nullable=False),
    sa.Column('isbp', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('answer',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('kakao_id', sa.String(length=10), nullable=False),
    sa.Column('checkdate', sa.Date(), nullable=True),
    sa.Column('checktime', sa.DateTime(), nullable=True),
    sa.Column('work_start_time', sa.String(length=10), nullable=True),
    sa.Column('work_end_time', sa.String(length=10), nullable=True),
    sa.Column('checkstatus', sa.String(length=10), nullable=False),
    sa.Column('workplace', sa.String(length=10), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('unusual', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kakao_id'], ['user.kakao_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('user')
    op.drop_table('server')
    # ### end Alembic commands ###
