"""empty message

Revision ID: ca01b7b2e68c
Revises: 29f0546eecf7
Create Date: 2021-01-10 17:05:19.005332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca01b7b2e68c'
down_revision = '29f0546eecf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isBp', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isBp')
    # ### end Alembic commands ###
