"""empty message

Revision ID: d7080f35829e
Revises: 61f9aaba6574
Create Date: 2021-01-11 00:32:53.192649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7080f35829e'
down_revision = '61f9aaba6574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('work_start_time', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'work_start_time')
    # ### end Alembic commands ###
