"""empty message

Revision ID: 29f0546eecf7
Revises: cddb1c992ea3
Create Date: 2021-01-10 16:56:54.107143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f0546eecf7'
down_revision = 'cddb1c992ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('firstSend', sa.Boolean(), nullable=True))
    op.add_column('server', sa.Column('secondSend', sa.Boolean(), nullable=True))
    op.add_column('server', sa.Column('thirdSend', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'thirdSend')
    op.drop_column('server', 'secondSend')
    op.drop_column('server', 'firstSend')
    # ### end Alembic commands ###
