"""empty message

Revision ID: 5264e6159af2
Revises: d7080f35829e
Create Date: 2021-01-13 22:39:49.274321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5264e6159af2'
down_revision = 'd7080f35829e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('work_end_time', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'work_end_time')
    # ### end Alembic commands ###
