"""empty message

Revision ID: 61f9aaba6574
Revises: ca01b7b2e68c
Create Date: 2021-01-10 17:22:42.640777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f9aaba6574'
down_revision = 'ca01b7b2e68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isbp', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isbp')
    # ### end Alembic commands ###
